#!/usr/bin/env python3

from os import environ
from os.path import join

WD = environ["WD"]


def read(filename):
    with open(filename, "r") as file:
        return file.read()


def write(string, filename):
    with open(filename, "w") as file:
        file.write(string)


def main():
    html = read(join(WD, "src", "index.html"))
    shaders = {
        "vertex": read(join(WD, "src", "shader.vert")),
        "fragment": read(join(WD, "src", "shader.frag")),
    }
    for key in shaders.keys():
        shaders[key] = " ".join(shaders[key].replace("\n", " ").split())
    write(html.format(**shaders), join(WD, "index.html"))


if __name__ == "__main__":
    main()
